const mongoose=require('mongoose');
const Schema=mongoose.Schema;
var newschema={
    name:{
        type:String,
        trim:true,
        required:true
    },
    email:{
        type:String,
        trim:true,
        required:true
    },
    gender:{
        type:String,
        trim:true,
        required:true
    },
    address:{
        type:String,
        trim:true,
        required:true
    },
    position:{
        type:String,
        trim:true,
        required:true
    },
    reportto:{
        type:String,
        trim:true,
        required:true
    },
    employmenttype:{
        type:String,
        trim:true,
        required:true
    },
    startdate:{
        type:Date,
        trim:true,
        required:true
    },
    dob:{
        type:Date,
        trim:true,
        required:true
    },
    image:{
        type:String,
        trim:true,
        required:true
    },
    password:{
        type:String,
        trim:true,
        required:true
    },
    mobile:{
        type:String,
        trim:true,
        required:true
    },
    d_id:{
        type:Schema.Types.ObjectId,
        ref:"departments",
    }

}
module.exports=Employee=mongoose.model('employees',newschema)